language: java
before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
install: mvn clean verify -DskipTests=true -B -q
script: mvn clean verify -B -q
sudo: false
cache:
  directories:
    - $HOME/.m2
    - $HOME/build/wala/WALA/com.ibm.wala.cast.java.polyglot/lib