language: java
before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - "git clone https://github.com/secure-software-engineering/DroidBench.git"
 - "export DROID_BENCH_ROOT=`pwd`/DroidBench"
 - "echo $DROID_BENCH_ROOT"
install: mvn clean verify -DskipTests=true -B -q
script: mvn clean verify -B -q
sudo: false
cache:
  directories:
    - $HOME/.m2
    - $HOME/build/wala/WALA/com.ibm.wala.cast.java.polyglot/lib
    - $HOME/build/wala/WALA/com.ibm.wala.core.testdata/ocaml/ocamljava-2.0-alpha1/lib